---
deployment:
  tasks:
    - /bin/rm -rf /home/nicher/public_html/product
    - /bin/cp -R dist/* /home/nicher/public_html/
    - /bin/cp dist/.htaccess /home/nicher/public_html/.htaccess
    - /bin/cp .user.ini /home/nicher/public_html/.user.ini