-- =========================================================
-- NICHERZ — Custom Orders (سفارش اختصاصی)
--
-- Run this file ONCE in the Supabase SQL Editor
-- (Dashboard → SQL → New query → paste → Run).
-- The script is idempotent and safe to re-run.
--
-- What it creates:
--   1) public.custom_order_products  — server-side price catalog
--   2) public.custom_orders          — customer custom-order requests
--      (linked to a normal checkout order via order_id)
--   3) Trigger that forces price/status from the server catalog
--      (client-submitted price/status are never trusted)
--   4) RPC public.create_custom_order — creates a real order +
--      order_items + custom_orders row so checkout/payment work
--   5) Row Level Security policies
--   6) Private storage bucket `custom_order_designs` + policies
--      for customer design/reference image uploads
-- =========================================================


-- =========================================================
-- 1) CUSTOM ORDER PRICE CATALOG
-- =========================================================

create table if not exists public.custom_order_products (
    code        text primary key,
    label_fa    text not null,
    price       numeric(12,2) not null,
    is_active   boolean not null default true,
    created_at  timestamptz not null default now(),
    constraint custom_order_products_code_check
        check (code in ('plaque', 'album')),
    constraint custom_order_products_price_check
        check (price > 0)
);

insert into public.custom_order_products (code, label_fa, price)
values
    ('plaque', 'پلاک با طرح دلخواه', 380000),
    ('album',  'آلبوم با طرح دلخواه', 550000)
on conflict (code) do nothing;

grant select on table public.custom_order_products to authenticated;

alter table public.custom_order_products enable row level security;

drop policy if exists "Public can view custom order catalog" on public.custom_order_products;
create policy "Public can view custom order catalog"
    on public.custom_order_products
    for select
    to authenticated, anon
    using (is_active = true);


-- =========================================================
-- 2) CUSTOM ORDERS TABLE
-- =========================================================
-- Prices are stored with each request at submission time so a
-- future catalog price change never rewrites historical orders.
-- order_id links the design request to the paid checkout order.

create table if not exists public.custom_orders (
    id              bigint generated by default as identity primary key,
    user_id         uuid not null default auth.uid()
                        references auth.users(id) on delete cascade,
    custom_type     text not null,
    product_label   text not null default '',
    price           numeric(12,2) not null default 0,
    status          text not null default 'pending',
    contact_name    text,
    contact_phone   text,
    artist_name     text,
    album_name      text,
    design_title    text,
    description     text,
    image_path      text,
    admin_note      text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),

    constraint custom_orders_type_check
        check (custom_type in ('plaque', 'album')),
    constraint custom_orders_status_check
        check (status in ('pending', 'approved', 'rejected', 'completed')),
    constraint custom_orders_price_check
        check (price > 0),
    constraint custom_orders_contact_name_check
        check (contact_name is null or char_length(contact_name) <= 120),
    constraint custom_orders_contact_phone_check
        check (contact_phone is null or char_length(contact_phone) <= 30),
    constraint custom_orders_artist_check
        check (artist_name is null or char_length(artist_name) <= 160),
    constraint custom_orders_album_check
        check (album_name is null or char_length(album_name) <= 160),
    constraint custom_orders_design_title_check
        check (design_title is null or char_length(design_title) <= 200),
    constraint custom_orders_description_check
        check (description is null or char_length(description) <= 3000),
    constraint custom_orders_image_path_check
        check (image_path is null or char_length(image_path) <= 500),
    constraint custom_orders_admin_note_check
        check (admin_note is null or char_length(admin_note) <= 2000)
);

alter table public.custom_orders
    add column if not exists order_id bigint
        references public.orders(id) on delete set null;

create index if not exists custom_orders_user_id_idx
    on public.custom_orders (user_id, created_at desc);

create index if not exists custom_orders_status_idx
    on public.custom_orders (status, created_at desc);

create index if not exists custom_orders_order_id_idx
    on public.custom_orders (order_id);

grant select, insert, update on table public.custom_orders to authenticated;


-- =========================================================
-- 3) SERVER-SIDE PRICE / STATUS ENFORCEMENT
-- =========================================================

create or replace function public.custom_orders_before_write()
returns trigger
language plpgsql
security definer
set search_path to public
as $$
declare
    catalog_row public.custom_order_products%rowtype;
begin
    if tg_op = 'INSERT' then
        -- The signed-in customer always owns their request.
        new.user_id := auth.uid();
        if new.user_id is null then
            raise exception 'authentication required';
        end if;

        -- A new request always starts as pending; clients cannot
        -- submit admin notes or a pre-approved status.
        new.status := 'pending';
        new.admin_note := null;

        select *
        into catalog_row
        from public.custom_order_products
        where code = new.custom_type
          and is_active = true;

        if not found then
            raise exception 'unknown custom order type';
        end if;

        -- Price and label always come from the server-side catalog.
        new.product_label := catalog_row.label_fa;
        new.price := catalog_row.price;
        new.updated_at := now();
    elsif tg_op = 'UPDATE' then
        -- Core request data is immutable after submission.
        if new.user_id is distinct from old.user_id
            or new.custom_type is distinct from old.custom_type
            or new.product_label is distinct from old.product_label
            or new.price is distinct from old.price
            or new.image_path is distinct from old.image_path
            or new.created_at is distinct from old.created_at
            or new.order_id is distinct from old.order_id then
            raise exception 'immutable custom order field';
        end if;
        new.updated_at := now();
    end if;

    return new;
end;
$$;

grant execute on function public.custom_orders_before_write() to authenticated;

drop trigger if exists custom_orders_before_write on public.custom_orders;
create trigger custom_orders_before_write
    before insert or update on public.custom_orders
    for each row
    execute function public.custom_orders_before_write();


-- =========================================================
-- 4) CREATE CUSTOM ORDER (checkout + payment path)
-- =========================================================
-- Creates a normal pending/unpaid order, one order_items row,
-- and a custom_orders design request linked by order_id.
-- Price always comes from the server catalog.

create or replace function public.create_custom_order(
    p_custom_type text,
    p_contact_name text,
    p_contact_phone text,
    p_shipping_name text,
    p_shipping_phone text,
    p_shipping_address text,
    p_shipping_postal_code text default null,
    p_artist_name text default null,
    p_album_name text default null,
    p_design_title text default null,
    p_description text default null,
    p_image_path text default null,
    p_shipping numeric default 0
)
returns bigint
language plpgsql
security definer
set search_path to public
as $$
declare
    v_user_id uuid;
    v_catalog public.custom_order_products%rowtype;
    v_order_id bigint;
    v_price numeric;
    v_shipping numeric;
    v_total numeric;
    v_type text;
    v_has_postal boolean;
begin
    v_user_id := auth.uid();
    if v_user_id is null then
        raise exception 'You must be logged in';
    end if;

    v_type := lower(trim(coalesce(p_custom_type, '')));
    if v_type not in ('plaque', 'album') then
        raise exception 'unknown custom order type';
    end if;

    if trim(coalesce(p_contact_name, '')) = '' then
        raise exception 'Contact name is required';
    end if;

    if trim(coalesce(p_contact_phone, '')) = '' then
        raise exception 'Contact phone is required';
    end if;

    if trim(coalesce(p_shipping_name, '')) = '' then
        raise exception 'Shipping name is required';
    end if;

    if trim(coalesce(p_shipping_phone, '')) = '' then
        raise exception 'Shipping phone is required';
    end if;

    if trim(coalesce(p_shipping_address, '')) = '' then
        raise exception 'Shipping address is required';
    end if;

    if coalesce(p_shipping, 0) < 0 then
        raise exception 'Invalid order amounts';
    end if;

    if p_image_path is not null then
        if length(p_image_path) > 500 then
            raise exception 'Invalid image path';
        end if;
        if position(v_user_id::text || '/' in p_image_path) <> 1 then
            raise exception 'Invalid image path';
        end if;
    end if;

    select *
    into v_catalog
    from public.custom_order_products
    where code = v_type
      and is_active = true;

    if not found then
        raise exception 'unknown custom order type';
    end if;

    v_price := v_catalog.price;
    v_shipping := coalesce(p_shipping, 0);
    v_total := v_price + v_shipping;

    insert into public.orders (
        user_id,
        status,
        payment_status,
        subtotal,
        shipping,
        tax,
        discount,
        total,
        currency,
        shipping_name,
        shipping_phone,
        shipping_address
    )
    values (
        v_user_id,
        'pending',
        'unpaid',
        v_price,
        v_shipping,
        0,
        0,
        v_total,
        'IRR',
        trim(p_shipping_name),
        trim(p_shipping_phone),
        trim(p_shipping_address)
    )
    returning id into v_order_id;

    select exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'orders'
          and column_name = 'postal_code'
    ) into v_has_postal;

    if v_has_postal then
        update public.orders
        set postal_code = nullif(trim(coalesce(p_shipping_postal_code, '')), '')
        where id = v_order_id;
    end if;

    -- Keep checkout/payment happy if order_number was not filled by a trigger.
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'orders'
          and column_name = 'order_number'
    ) then
        update public.orders
        set order_number = coalesce(
            nullif(trim(coalesce(order_number, '')), ''),
            'NCH' || to_char(now(), 'YYMMDD') || lpad(v_order_id::text, 6, '0')
        )
        where id = v_order_id;
    end if;

    insert into public.order_items (
        order_id,
        product_variant_id,
        product_name,
        sku,
        quantity,
        unit_price,
        total_price
    )
    values (
        v_order_id,
        null,
        v_catalog.label_fa,
        'CUSTOM-' || upper(v_type),
        1,
        v_price,
        v_price
    );

    insert into public.custom_orders (
        user_id,
        custom_type,
        contact_name,
        contact_phone,
        artist_name,
        album_name,
        design_title,
        description,
        image_path,
        order_id
    )
    values (
        v_user_id,
        v_type,
        nullif(trim(coalesce(p_contact_name, '')), ''),
        nullif(trim(coalesce(p_contact_phone, '')), ''),
        nullif(trim(coalesce(p_artist_name, '')), ''),
        nullif(trim(coalesce(p_album_name, '')), ''),
        nullif(trim(coalesce(p_design_title, '')), ''),
        nullif(trim(coalesce(p_description, '')), ''),
        p_image_path,
        v_order_id
    );

    return v_order_id;
end;
$$;

revoke execute on function public.create_custom_order(text, text, text, text, text, text, text, text, text, text, text, text, numeric) from public, anon;
grant execute on function public.create_custom_order(text, text, text, text, text, text, text, text, text, text, text, text, numeric) to authenticated;


-- =========================================================
-- 5) ROW LEVEL SECURITY
-- =========================================================

alter table public.custom_orders enable row level security;

drop policy if exists "Users can create their own custom orders" on public.custom_orders;
create policy "Users can create their own custom orders"
    on public.custom_orders
    for insert
    to authenticated
    with check (
        user_id = (select auth.uid())
        and status = 'pending'
    );

drop policy if exists "Users and admins can view custom orders" on public.custom_orders;
create policy "Users and admins can view custom orders"
    on public.custom_orders
    for select
    to authenticated
    using (
        user_id = (select auth.uid())
        or public.is_admin()
    );

drop policy if exists "Admins can update custom orders" on public.custom_orders;
create policy "Admins can update custom orders"
    on public.custom_orders
    for update
    to authenticated
    using (public.is_admin())
    with check (public.is_admin());

-- No DELETE policy on purpose: requests are kept for the record.


-- =========================================================
-- 6) PRIVATE STORAGE BUCKET FOR DESIGN IMAGES
-- =========================================================
-- Bucket is private; images are accessed through short-lived
-- signed URLs by the owning customer and admins only.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'custom_order_designs',
    'custom_order_designs',
    false,
    5242880,  -- 5 MB
    array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Users can upload custom order designs" on storage.objects;
create policy "Users can upload custom order designs"
    on storage.objects
    for insert
    to authenticated
    with check (
        bucket_id = 'custom_order_designs'
        and (storage.foldername(name))[1] = (select auth.uid())::text
    );

drop policy if exists "Users and admins can view custom order designs" on storage.objects;
create policy "Users and admins can view custom order designs"
    on storage.objects
    for select
    to authenticated
    using (
        bucket_id = 'custom_order_designs'
        and (
            (storage.foldername(name))[1] = (select auth.uid())::text
            or public.is_admin()
        )
    );

drop policy if exists "Owners and admins can delete custom order designs" on storage.objects;
create policy "Owners and admins can delete custom order designs"
    on storage.objects
    for delete
    to authenticated
    using (
        bucket_id = 'custom_order_designs'
        and (
            (storage.foldername(name))[1] = (select auth.uid())::text
            or public.is_admin()
        )
    );
