import { supabase } from "./js/supabase.js";

const shellStyle = document.createElement("style");
shellStyle.textContent = `
  .shop-header-inner { display:flex !important; align-items:center !important; justify-content:space-between !important; width:min(94%,90em) !important; position:relative !important; }
  .shop-header .brand-wrap { order:1 !important; margin-right:auto !important; margin-left:0 !important; justify-self:start !important; }
  .shop-header .header-nav { order:2 !important; flex:1 1 auto !important; justify-content:center !important; }
  .shop-header .header-actions { order:3 !important; margin-left:auto !important; margin-right:0 !important; justify-self:end !important; }
  .shop-header .header-nav > a, .shop-header .brand-name, .shop-header .brand-copy small, .shop-header .cart-pill { font-family:"Metal Mania",cursive !important; }
  .shop-header .auth-action { border:1px solid #fff !important; padding:.45em .7em !important; }
  .shop-header .header-nav > a::before, .shop-header .auth-nav a::before { display:none !important; content:none !important; }
  .shop-header .header-nav > a, .shop-header .cart-pill, .shop-header .brand-wrap { position:relative !important; transition:color .25s ease,transform .25s ease,text-shadow .25s ease,border-color .25s ease,box-shadow .25s ease !important; }
  .shop-header .header-nav > a::after { content:"" !important; display:block !important; position:absolute !important; left:50% !important; bottom:-.35em !important; width:0 !important; height:1px !important; background:#e1bd2b !important; transform:translateX(-50%) !important; transition:width .25s ease !important; }
  .shop-header .header-nav > a:hover, .shop-header .cart-pill:hover, .shop-header .brand-wrap:hover { color:#e1bd2b !important; transform:translateY(-2px) !important; text-shadow:0 0 12px rgba(225,189,43,.42) !important; }
  .shop-header .header-nav > a:hover::after { width:75% !important; }
  .shop-header .cart-pill:hover { border-color:#e1bd2b !important; box-shadow:0 0 18px rgba(225,189,43,.2) !important; }
  .shop-header .brand-wrap:hover .brand-name { color:#e1bd2b !important; }
  .shop-header-inner > .container { position:absolute !important; left:50% !important; top:50% !important; transform:translate(-50%,-50%) !important; z-index:20 !important; display:flex !important; }
  .shop-header .brand-mark, .shop-header .cart-pill { position:relative !important; overflow:hidden !important; isolation:isolate !important; }
  .shop-header .brand-mark::after, .shop-header .cart-pill::before { content:"" !important; position:absolute !important; inset:-35% -70% !important; pointer-events:none !important; z-index:10 !important; background:linear-gradient(120deg,transparent 34%,rgba(255,255,255,.18) 45%,rgba(255,255,255,.95) 50%,rgba(255,255,255,.18) 55%,transparent 66%) !important; transform:translateX(-135%) rotate(14deg) !important; animation:nicherzHeaderShimmer 5.8s cubic-bezier(.45,0,.2,1) infinite !important; }
  @keyframes nicherzHeaderShimmer { 0%,48%{transform:translateX(-135%) rotate(14deg);opacity:0} 56%{opacity:.95} 72%{transform:translateX(135%) rotate(14deg);opacity:.95} 82%,100%{transform:translateX(135%) rotate(14deg);opacity:0} }
  .shop-page .product-card { position:relative !important; overflow:hidden !important; isolation:isolate !important; }
  .shop-page .product-card::after { content:"" !important; position:absolute !important; inset:-45% !important; z-index:20 !important; pointer-events:none !important; background:linear-gradient(120deg,transparent 37%,rgba(255,255,255,.16) 46%,rgba(255,255,255,.88) 50%,rgba(255,255,255,.16) 54%,transparent 63%) !important; transform:translateX(-135%) rotate(14deg) !important; animation:nicherzProductShimmer 5.8s cubic-bezier(.45,0,.2,1) infinite !important; }
  @keyframes nicherzProductShimmer { 0%,48%{transform:translateX(-135%) rotate(14deg);opacity:0} 56%{opacity:.75} 72%{transform:translateX(135%) rotate(14deg);opacity:.75} 82%,100%{transform:translateX(135%) rotate(14deg);opacity:0} }
  .cart-page { padding-top:1.6em !important; }
  .continue-shopping-link { display:inline-flex !important; align-items:center !important; justify-content:center !important; gap:.45em !important; margin-top:1.6em !important; padding:.7em 1.05em !important; border:1px solid rgba(225,189,43,.45) !important; border-radius:.55em !important; color:white !important; background:rgb(37, 37, 37) !important; text-decoration:none !important; font-family:"Metal Mania",cursive !important; letter-spacing:.06em !important; }
  .shop-footer { width:100% !important; margin-top:2em !important; background:rgba(5,5,5,.96) !important; border-top:1px solid rgba(255,255,255,.14) !important; box-shadow:0 -12px 35px rgba(0,0,0,.3) !important; }
  .shop-footer .footer-grid { width:min(94%,90em) !important; margin:0 auto !important; padding:3em 0 2.4em !important; display:grid !important; grid-template-columns:1.5fr 1fr 1fr !important; gap:2em !important; }
  .shop-footer .footer-logo { display:none !important; }
  .shop-footer .footer-brand h3,.shop-footer .footer-links h4,.shop-footer .footer-links a,.shop-footer .footer-bottom,.shop-footer .footer-bottom span { font-family:"Metal Mania",cursive !important; }
  .shop-footer .footer-brand h3 { margin:0 0 .35em !important; color:#fff !important; font-size:1.35em !important; }
  .shop-footer .footer-brand p { margin:0 !important; color:#e1bd2b !important; font-family:Arial,sans-serif !important; font-size:.72em !important; }
  .shop-footer .footer-links { display:flex !important; flex-direction:column !important; gap:.45em !important; }
  .shop-footer .footer-links h4 { margin:0 0 .35em !important; color:#fff !important; font-size:.78em !important; }
  .shop-footer .footer-links a,.shop-footer .footer-links a:link,.shop-footer .footer-links a:visited { color:#fff !important; font-size:.72em !important; text-decoration:none !important; }
  .shop-footer .footer-bottom { width:min(94%,90em) !important; margin:0 auto !important; padding:1em 0 1.35em !important; display:flex !important; justify-content:space-between !important; color:rgba(255,255,255,.62) !important; font-size:.62em !important; border-top:1px solid rgba(255,255,255,.08) !important; }

  .nicherz-account-drawer-tab { position:fixed !important; right:0 !important; top:42% !important; transform:translateY(-50%) !important; z-index:9998 !important; writing-mode:vertical-rl !important; text-orientation:mixed !important; padding:1.1em .65em !important; border:1px solid rgba(225,189,43,.55) !important; border-right:0 !important; border-radius:1em 0 0 1em !important; background:rgba(10,10,10,.88) !important; color:#e1bd2b !important; font:.72em "Metal Mania",cursive !important; letter-spacing:.12em !important; cursor:pointer !important; box-shadow:0 0 24px rgba(225,189,43,.12) !important; backdrop-filter:blur(12px) !important; }
  .nicherz-account-drawer-tab:hover { background:#e1bd2b !important; color:#111 !important; }
  .nicherz-account-drawer { position:fixed !important; top:0 !important; right:0 !important; width:min(23em,88vw) !important; height:100vh !important; z-index:9999 !important; transform:translateX(105%) !important; transition:transform .35s cubic-bezier(.22,.8,.2,1) !important; background:linear-gradient(145deg,rgba(18,18,18,.98),rgba(4,4,4,.98)) !important; border-left:1px solid rgba(225,189,43,.3) !important; box-shadow:-18px 0 55px rgba(0,0,0,.55) !important; padding:5.5em 1.3em 1.5em !important; box-sizing:border-box !important; }
  .nicherz-account-drawer.is-open { transform:translateX(0) !important; }
  .nicherz-account-drawer .drawer-title { color:#e1bd2b !important; font:1.15em "Metal Mania",cursive !important; letter-spacing:.1em !important; margin:0 0 .3em !important; }
  .nicherz-account-drawer .drawer-subtitle { color:rgba(255,255,255,.5) !important; font:.65em Arial,sans-serif !important; margin:0 0 2em !important; }
  .nicherz-account-drawer a,.nicherz-account-drawer button { display:flex !important; justify-content:space-between !important; width:100% !important; box-sizing:border-box !important; padding:1em .8em !important; margin:.35em 0 !important; border:1px solid rgba(255,255,255,.1) !important; border-radius:.5em !important; background:rgba(255,255,255,.035) !important; color:#fff !important; text-decoration:none !important; font:.72em "Metal Mania",cursive !important; letter-spacing:.06em !important; cursor:pointer !important; }
  .nicherz-account-drawer a:hover,.nicherz-account-drawer button:hover { color:#111 !important; background:#e1bd2b !important; border-color:#e1bd2b !important; }
  .nicherz-account-drawer .drawer-close { position:absolute !important; top:1.2em !important; right:1.2em !important; width:auto !important; border:0 !important; background:transparent !important; font-size:1.2em !important; color:#fff !important; }
  .nicherz-account-drawer-backdrop { position:fixed !important; inset:0 !important; z-index:9998 !important; background:rgba(0,0,0,.58) !important; opacity:0 !important; pointer-events:none !important; transition:opacity .3s ease !important; }
  .nicherz-account-drawer-backdrop.is-open { opacity:1 !important; pointer-events:auto !important; }
  @media(max-width:700px){
    .shop-header-inner{width:94%!important;display:grid!important;grid-template-columns:1fr 1fr 1fr!important;grid-template-rows:auto auto!important;gap:.7em .45em!important}
    .shop-header .brand-wrap{grid-column:1!important;grid-row:1!important}.shop-header .header-actions{grid-column:3!important;grid-row:1!important}.shop-header .header-nav{grid-column:1/-1!important;grid-row:2!important;overflow-x:auto!important;justify-content:center!important;gap:.75em!important}.shop-header-inner>.container{position:static!important;grid-column:2!important;grid-row:1!important;transform:none!important;width:100%!important}.shop-header-inner>.container input{width:100%!important;box-sizing:border-box!important}
    .shop-footer .footer-grid{grid-template-columns:1.35fr .825fr .825fr!important;gap:.55em!important;width:94%!important;padding:2.2em 0 1.6em!important}.shop-footer .footer-bottom{width:94%!important;font-size:.58em!important}
    .nicherz-account-drawer-tab{top:45%;font-size:.64em!important;padding:.9em .55em!important}.nicherz-account-drawer{width:min(21em,88vw)!important}
  }
`;
document.head.appendChild(shellStyle);

function currentRoute(){const path=(window.location.pathname||"/").replace(/\/+$/,"")||"/";return path==="/home"?"/":path;}
function isHomePage(){return currentRoute()==="/";}
async function getSession(){const {data,error}=await supabase.auth.getSession();if(error){console.error("Could not read auth session:",error);return null;}return data?.session||null;}
function placeHomeSearch(){const header=document.querySelector(".shop-header"),nav=header?.querySelector(".header-nav"),inner=header?.querySelector(".shop-header-inner");if(!nav||!inner||!isHomePage())return;const search=inner.querySelector(".container")||nav.querySelector(".container");if(!search)return;if(search.parentElement!==inner)inner.appendChild(search);search.style.setProperty("display","flex","important");}
async function rebuildHeader(){const header=document.querySelector(".shop-header"),nav=header?.querySelector(".header-nav"),inner=header?.querySelector(".shop-header-inner");if(!nav||!inner)return;const search=inner.querySelector(".container")||nav.querySelector(".container"),session=await getSession(),authLabel=session?"LOGOUT":"LOGIN";nav.innerHTML=`<a href="/">HOME</a><a href="/shop">PRODUCT</a><a href="/#gallery">GALLERY</a><a href="/account">ACCOUNT</a><a href="${session?"#logout":"/login"}" class="auth-action" data-auth-action>${authLabel}</a>`;if(search){inner.appendChild(search);search.style.setProperty("display",isHomePage()?"flex":"none","important");}const currentPath=currentRoute();nav.querySelectorAll("a:not(.auth-action)").forEach(link=>{const href=link.getAttribute("href")||"";if(href.includes("#"))return;const hrefPath=(href.split("?")[0]||"/").replace(/\/+$/,"")||"/";if(hrefPath===currentPath){link.classList.add("active-nav");link.setAttribute("aria-current","page");}});placeHomeSearch();}
function rebuildFooter(){document.querySelectorAll(".shop-footer").forEach(footer=>{let grid=footer.querySelector(".footer-grid");if(!grid){grid=document.createElement("div");grid.className="footer-grid";const bottom=footer.querySelector(".footer-bottom");if(bottom)footer.insertBefore(grid,bottom);else footer.appendChild(grid);}grid.innerHTML=`<div class="footer-brand"><div><h3>NICHERZ</h3><p>Curated chaos for the loudest souls.</p></div></div><div class="footer-links"><h4>INFO</h4><a href="/contact">Contact</a><a href="#">Support</a></div><div class="footer-links"><h4>FOLLOW</h4><a href="https://instagram.com/nicherzz" target="_blank" rel="noopener noreferrer">Instagram</a><a href="https://t.me/nicherz" target="_blank" rel="noopener noreferrer">Telegram</a></div>`;let bottom=footer.querySelector(".footer-bottom");if(!bottom){bottom=document.createElement("div");bottom.className="footer-bottom";footer.appendChild(bottom);}bottom.innerHTML=`<span>© 2026 NICHERZ</span><span>WEAR THE LEGEND</span>`;});}
function rebuildAccountDrawer(){if(document.querySelector(".nicherz-account-drawer"))return;const tab=document.createElement("button");tab.className="nicherz-account-drawer-tab";tab.type="button";tab.textContent="ACCOUNT";tab.setAttribute("aria-label","Open account menu");const backdrop=document.createElement("div");backdrop.className="nicherz-account-drawer-backdrop";const drawer=document.createElement("aside");drawer.className="nicherz-account-drawer";drawer.setAttribute("aria-label","Account menu");drawer.innerHTML=`<button class="drawer-close" type="button" aria-label="Close account menu">×</button><h2 class="drawer-title">ACCOUNT ACCESS</h2><p class="drawer-subtitle">MANAGE YOUR NICHERZ EXPERIENCE</p><a href="/account"><span>PROFILE</span><span>→</span></a><a href="/orders"><span>MY ORDERS</span><span>→</span></a><a href="/orders"><span>ORDER STATUS</span><span>→</span></a><a href="/cart"><span>CART</span><span>→</span></a><a href="/account#profileForm"><span>PERSONAL INFORMATION</span><span>→</span></a><button type="button" data-drawer-logout><span>LOGOUT</span><span>→</span></button>`;document.body.append(tab,backdrop,drawer);const close=()=>{drawer.classList.remove("is-open");backdrop.classList.remove("is-open");};tab.addEventListener("click",()=>{drawer.classList.add("is-open");backdrop.classList.add("is-open")});backdrop.addEventListener("click",close);drawer.querySelector(".drawer-close").addEventListener("click",close);drawer.querySelector("[data-drawer-logout]").addEventListener("click",async()=>{const session=await getSession();if(!session){window.location.href="/login";return;}const {error}=await supabase.auth.signOut();if(!error)window.location.href="/shop";});}
async function handleAuthAction(event){const link=event.target.closest("[data-auth-action]");if(!link)return;const session=await getSession();if(!session)return;event.preventDefault();const {error}=await supabase.auth.signOut();if(!error)await rebuildHeader();}
document.addEventListener("click",handleAuthAction);
function normalizeRelatedProductLinks(root=document){root.querySelectorAll("a.Bio[href*='category=']").forEach(link=>{const url=new URL(link.href,window.location.href),category=url.searchParams.get("category");if(!band)return;url.searchParams.delete("category");url.searchParams.set("band",band);link.href=url.toString();});}
normalizeRelatedProductLinks();const bandsContainer=document.getElementById("bands-container");if(bandsContainer)new MutationObserver(()=>normalizeRelatedProductLinks(bandsContainer)).observe(bandsContainer,{childList:true,subtree:true});
function bootShell(){rebuildFooter();rebuildHeader();rebuildAccountDrawer();requestAnimationFrame(()=>{placeHomeSearch();rebuildFooter();});}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bootShell,{once:true});else bootShell();
if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", bootShell, { once: true }); else bootShell();
const accountLink = document.querySelector(".nicherz-account-drawer-tab");

const { data: { session } } = await supabase.auth.getSession();

if (!session) {
  accountLink.style.display = "none";
}

supabase.auth.onAuthStateChange(()=>{rebuildHeader();rebuildFooter();});
